apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
  labels:
    app: demo-voting-app
    name: postgres-sts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  serviceName: postgres-sts-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: postgres-pod  
      labels:
        app: demo-voting-app
        name: postgres-pod
    spec:
      containers:
      - name: postgres
        image: {{ .Values.image.postgres }}
        ports:
        - containerPort: {{ .Values.service.postgres.port }}
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
