apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: demo-voting-app
    name: postgres-service
spec:
  type: {{ .Values.service.postgresClusterIP.type }}
  ports:
  - port: {{ .Values.service.postgresClusterIP.port }}
    targetPort: {{ .Values.service.postgresClusterIP.port }}
  selector:
    app: demo-voting-app
    name: postgres-pod
