apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
    name: redis
spec: 
  type: {{ .Values.service.redisClusterIP.type }}
  ports:
  - port: {{ .Values.service.redisClusterIP.port }}
    targetPort: {{ .Values.service.redisClusterIP.port }}
  selector:
    app: demo-voting-app
    name: redis-pod
