apiVersion: v1
kind: Service
metadata:
  name: redis-sts-service
  labels:
    app: demo-voting-app
    name: redis-sts-service
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: {{ .Values.service.redis.port }}
    targetPort: {{ .Values.service.redis.port }}
  selector:
    app: demo-voting-app
    name: redis-pod
