apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    app: demo-voting-app
    name: redis-sts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-voting-app
      name: redis-pod
  serviceName: redis-sts-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: redis-pod
      labels:
        app: demo-voting-app
        name: redis-pod
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.redis }}
        ports:
        - containerPort: {{ .Values.service.redis.port }}
