apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
    name: result-service
spec:
  type: {{ .Values.service.resultApp.type }}
  ports:
  - port: {{ .Values.service.resultApp.port }}
    targetPort: {{ .Values.service.resultApp.port }}
  selector:
    app: demo-voting-app
    name: result-app-pod
