apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app
    name: worker-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: worker-app-pod
    spec:
      containers:
      - name: worker-app
        image: {{ .Values.image.workerApp }}
